name: nuisance
channels:
  - anaconda-fusion
  - defaults
dependencies:
  - python=3.7
  - jupyter=1.0.0
  - matplotlib>=3.1,<3.3
  - numpy>=1.18,<1.19
  - pandas>=1.0.3,<1.1
  - seaborn=0.10.1
  - statsmodels=0.11.1
